### PR TITLE
Dist bundling and testing

### PR DESCRIPTION
**Pull request by cavis**
Get dist javascript building and serving.  Also run tests using a bundled `main.ts`.

### CODE REVIEW

**Comment by cavis** [comment]
Added a simple Dockerfile, which can build a "production-ish" image.  No support for a hot-reload docker-compose dev server yet.

**Comment by kookster** [comment]
This also lgtm, @cavis do you want to handle the merge, or do you want me to?

**Comment by cavis** [comment]
I'm working through the merge.  Not as simple as I hoped!

**Comment by cavis** [comment]
Thar we go!

**Pull request merged**
