### PR TITLE
Get phantom working in alpine

### LINKED ISSUE #26: docker development mode
Current docker setup only supports serving precompiled assets.
- Make sure docker-compose correctly mounts dev `node_modules` back into the container.
- If it turns out we need `node-sass` in the container, may need to do something drastic.  Like caching the built binary somewhere, and moving it back when it's needed.
- Install `watchman`
- Map reload ports so webpack dev server works properly.

### PR DESCRIPTION
**Pull request by cavis**
Fixes #26.

- [x] Get phantomjs working in alpine
- [x] Get docker-compose tests working
- [x] Get docker-compose dev server working

Finally found an alpine+phantom project that works.  And doesn't require building from source.  Not quite as slick as a selenium/webdriver solution, but after struggling with that for awhile, I gave up.

This will install dev/optional dependencies into the docker container.  Which results in a slightly larger image.  But much better than non-alpine builds, which were pushing 1GB.

### CODE REVIEW

**Comment by kookster** [comment]
looks like id doesn't love .docker, did you have it running / browsing locally?

image

**Comment by cavis** [comment]
@kookster did you change your AUTH_CLIENT_ID?  (I think I noted that in the README ... it defaults to a prx.dev one right now)

**Comment by cavis** [comment]
Oh wait ... hold on this one.  Dev reloading not actually working.  (It's trying to hit `localhost:4201` from the browser ... rather than proxying that through `publish.prx.docker`).

**Comment by cavis** [comment]
Back in business!

**Pull request merged**
